#!/usr/bin/env python3

from argparse import ArgumentParser

from quire import Quire

opt = ArgumentParser()
opt.description = "Apply selected style to built pages."
arg = opt.add_argument
arg("STYLE", default="style", nargs="?", help="Read CSS files from this folder.")
arg("SHEET", default="proof/style.css", nargs="?", help="Save CSS to this file.")
opt = opt.parse_args()

print(f"A {opt.STYLE} by any other name would style as {opt.SHEET}.")
Quire.apply(opt.STYLE, opt.SHEET)
print(f"Exeunt {__file__}")

# Copyright © 2020 Sam Kennerly
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
