#!/usr/bin/env python3

from argparse import ArgumentParser

from quire import Quire

opt = ArgumentParser()
opt.description = "Build pages from HTML <main> elements."
arg = opt.add_argument
arg("PAGES", default="ready", nargs="?", help="Read pages from this folder.")
arg("SITE", default="proof", nargs="?", help="Save pages to this folder.")
opt = opt.parse_args()

print(f"O brave new {opt.SITE} that has {opt.PAGES} pages in it!")
Quire(opt.PAGES).build(opt.SITE)
print(f"Exeunt {__file__}")
"""
Copyright © 2019 Sam Kennerly

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
